apiVersion: apps/v1
kind: Deployment
metadata:
  name: bit2me-mongo-deployment
  labels:
    name: bit2me-mongo-deployment
    tier: bit2me-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: bit2me-mongo
  template:
    metadata:
      name: bit2me-mongo-deployment
      labels:
        tier: bit2me-mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bit2me-redis-deployment
  labels:
    name: bit2me-redis-deployment
    tier: bit2me-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: bit2me-redis
  template:
    metadata:
      name: bit2me-redis-deployment
      labels:
        tier: bit2me-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bit2me-web-deployment
  labels:
    name: bit2me-web-deployment
    tier: bit2me-web
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: bit2me-web
  template:
    metadata:
      name: bit2me-web-deployment
      labels:
        tier: bit2me-web
    spec:
      containers:
        - name: web-app
          image: diegomgar/bit2me-web-app
          env:
            - name: BIT2ME_COINMARKETCAP_API_KEY
              value: dummytext
            - name: BIT2ME_SESUSER
              value: dummytext
            - name: BIT2ME_SESPASSWORD
              value: dummytext
            - name: BIT2ME_EXPRESS_PORT
              value: "8080"
            - name: BIT2ME_MONGOHOST
              value: "mongo"
            - name: BIT2ME_REDISHOST
              value: "redis"
